### ISSUE TITLE
Disclaimer for Organizations for Monthly Cost Allocation Report

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cost-management-user-guide#11]
This information is all useful for accounts that are not linked through organizations, but it might be useful to have a disclaimer for organizations that the settings and ability to manage may look different - that may be a link to the organizations docs or documentation here.

**Comment by amiito** [comment]
Hi, thank you for callout. The AWS service teams are looking into your callout, and are receptive to the feedback. Upon confirmation, the change will be added to the documentation in a future update.
