### ISSUE TITLE
Offer Index File Schema is Incorrect

### ISSUE THREAD

**Issue by hakenmt** [awsdocs/aws-cost-management-user-guide#21]
The docs have this listed for an offer [here](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/reading-the-offer-index.html)

```json
"firstService":{
             "offerCode":{
             "offerCode":"The service that this price list is for",
             "currentVersionUrl":"The URL for this offer file",
             "currentRegionIndexUrl":"The URL for the regional offer index file"
             "savingsPlanVersionIndexUrl":"The URL for the Savings Plan index file (if applicable)"
        },
```
This is incorrect, the actual schema is:

```json
"firstService":{
             "offerCode":"The service that this price list is for",
             "versionIndexUrl" : "The URL for the versions of the offer index file",
             "currentVersionUrl":"The URL for this offer file",
             "currentRegionIndexUrl":"The URL for the regional offer index file"
             "savingsPlanVersionIndexUrl":"The URL for the Savings Plan index file (if applicable)",
             "currentSavingsPlanIndexUrl":"The URL for the current regional Savings Plan index (if applicable)"
        },
```
The description of the schema also needs to be updated to reflect these differences.

**Comment by amiito** [comment]
Thank you for your request. A member of the service team will be working on it and will provide updates here about progress.

**Comment by amiito** [comment]
The service team's confirmed the current example reflects the operation. They'll look into your suggestion further for any one-off use-cases that should be included in the document. Once there are findings, changes will be made in a future update.

**Comment by hakenmt** [comment]
That can’t possibly be true. The schema in the example isn’t even valid JSON. The first property ‘offerCode’ has an open brace that isn’t closed and is then repeated. You are also missing the ‘currentSavingsPlanIndexUrl’ property. It takes like 5 minutes to download the EC2 offer file and see that the documentation is obviously incorrect. mhaken@ if you want to connect.
