### ISSUE TITLE
I am getting charged

### ISSUE THREAD

**Issue by rifaterdemsahin** [awsdocs/aws-cost-management-user-guide#22]
I could not locate where to ask where to connect...

My card is getting billed but i cant open a support task.

**Comment by amiito** [comment]
Hi, 
This feedback mechanism is specific to the AWS Billing and Cost Management documentation, and is not shared with Customer Support. You can contact AWS Support about your charges by following the directions here: 
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-get-answers.html 

If you’re having problems logging into your AWS account, you can also contact Customer Support from the following page:
https://pages.awscloud.com/contact-us-account-support.html
