### ISSUE TITLE
I’m locked out of my aim account it’s saying to go to billing can’t remember my codes

### ISSUE THREAD

**Issue by toddlew** [awsdocs/aws-cost-management-user-guide#24]

**Comment by amiito** [comment]
Hi, 

To regain access to your AWS account, please contact AWS Support. You can can contact AWS Support using the following steps, to log in to your AWS account. 
1. Go to the "I'm an AWS customer and I'm looking for billing or account support" page here: https://pages.awscloud.com/contact-us-account-support.html
2. Fill out the form. 
3. Choose Submit.
