### ISSUE TITLE
Typo published, not in master

### ISSUE THREAD

**Issue by lvdh** [awsdocs/aws-cost-management-user-guide#9]
At this moment, the "[Understanding Consolidated Bills](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/con-bill-blended-rates.html#Blended_CB)" page shows a note under "[Blended Rates and Costs](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/con-bill-blended-rates.html#Blended_CB)":

> Blended rates are the averaged rates of the Reserved Instances and On-Demand Instances that are used by member accounts in an organization in AWS Organizations. AWS calculates blended costs by multiplying the blended rate for each service with an account’s usage of that service.
> 
> **_Note_**
> 
> _AWS shows each linked account thier charges as unblended costs. AWS continues to apply all of the consolidated billing benefits such as reservations and tiered prices across all linked accounts in an AWS Organizations organization._
> 
> This section includes examples that show how AWS calculates blended rates for the following services.

However, the [latest master commit at this time](https://github.com/awsdocs/aws-cost-management-user-guide/blob/ee49f1b417ad21293280f9119641a96c42f60616/doc_source/con-bill-blended-rates.md#Blended_CB) reads:

> Blended rates are the averaged rates of the Reserved Instances and On-Demand Instances that are used by member accounts in an organization in AWS Organizations. AWS calculates blended costs by multiplying the blended rate for each service with an account’s usage of that service. This section includes examples that show how AWS calculates blended rates for the following services:

Originally I intended to create a PR for the typo (the note spells "thier" vs "their"). However, the note with the typo is not present in the current master branch.

Is it expected for the publication to be out of sync with master?

**Comment by amiito** [comment]
Thank you for your callout. The documentation and master are regularly synced. However, there seems to be a gap in the updates for the recent billing documentation. I will schedule a master sync within the next few business days. I appreciate your patience as we identified the root cause of this issue.
